//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicMedicalRecords.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class CayMau
    {
        public int ID { get; set; }
        public string ResultNuoiCay { get; set; }
        public string ImageNuoiCay { get; set; }
        public string ResultDinhDanh { get; set; }
        public string ImageDinhDanh { get; set; }
        public string NongDo { get; set; }
        public Nullable<int> InformationExamination_ID { get; set; }
        public bool ChiDinh { get; set; }
        public HttpPostedFileBase[] ImageNuoiCayFiles { get; set; }
        public HttpPostedFileBase[] ImageDinhDanhFiles { get; set; }

        public string[] ExistImageNC { get; set; }
        public string[] ExistImageDD { get; set; }
        public virtual InformationExamination InformationExamination { get; set; }
    }
}
