//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicMedicalRecords.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTMau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTMau()
        {
            this.Detail_CTMau = new HashSet<Detail_CTMau>();
        }
    
        public int ID { get; set; }
        public bool ChiDinh { get; set; }
        public string NameTest { get; set; }
        public Nullable<double> Result { get; set; }
        public string CSBT { get; set; }
        public string Unit { get; set; }
        public string MayXN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail_CTMau> Detail_CTMau { get; set; }
    }
}
