//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicMedicalRecords.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostic
    {
        public int ID { get; set; }
        public Nullable<int> DiagnosticCategory_ID { get; set; }
        public Nullable<int> Prescription_ID { get; set; }
    
        public virtual DiagnosticsCategory DiagnosticsCategory { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
