//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicMedicalRecords.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DongMau
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Result { get; set; }
        public string Normal { get; set; }
        public string Unit { get; set; }
    }
}
