//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicMedicalRecords.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformationExamination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InformationExamination()
        {
            this.Clinicals = new HashSet<Clinical>();
            this.MedicalTestsPrescriptions = new HashSet<MedicalTestsPrescription>();
            this.Prescriptions = new HashSet<Prescription>();
            this.Subclinicals = new HashSet<Subclinical>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DateExamine { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> HeartBeat { get; set; }
        public Nullable<int> Breathing { get; set; }
        public Nullable<int> BloodPressure { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<int> PatientStatus_ID { get; set; }
        public Nullable<int> Patient_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clinical> Clinicals { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual PatientStatu PatientStatu { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalTestsPrescription> MedicalTestsPrescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subclinical> Subclinicals { get; set; }
    }
}
