//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicMedicalRecords.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription_Detail
    {
        public int ID { get; set; }
        public Nullable<int> NumMedication { get; set; }
        public string Note { get; set; }
        public Nullable<int> Medication_ID { get; set; }
        public Nullable<int> Precription__ID { get; set; }
    
        public virtual Medication Medication { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
